name: Build New Release

on: [push, release]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-docker-release:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Java Environment'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 'Build Image'
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_URL: ${{secrets.DB_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
        run: |
          java --version
          javac --version
          chmod +x mvnw 
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${REGISTRY}/${IMAGE_NAME}:dev

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: 'Tag Image'
        # check if tags exist
        if: steps.meta.outputs.tags != ''
        run: |
          docker tag ${REGISTRY}/${IMAGE_NAME}:dev ${REGISTRY}/${IMAGE_NAME}:${{ steps.meta.outputs.tags }}

      - name: 'Push Image'
        run: |
          docker image ls
          docker images
          docker push ${REGISTRY}/${IMAGE_NAME}:dev
